name: Apps

on:
    push:
        branches: [ master ]
        paths:
            - "src/Sitko.Core.App/**"
            - "tests/Sitko.Core.App.Tests/**"
            - ".github/workflows/apps.yml"
    pull_request:
        branches: [ master ]
        paths:
            - "src/Sitko.Core.App/**"
            - "tests/Sitko.Core.App.Tests/**"
            - ".github/workflows/apps.yml"

jobs:
    build:
        runs-on: ubuntu-latest
        container: ghcr.io/sitkoru/actions-container
        steps:
            -   uses: actions/checkout@v2.3.4
            -   uses: actions/setup-dotnet@v1.8.0
                with:
                    dotnet-version: '3.1.x'
            -   uses: actions/setup-dotnet@v1.8.0
                with:
                    dotnet-version: '5.0.x'
            -   name: Add Github Actions logger
                run: dotnet add src/Sitko.Core.Xunit/Sitko.Core.Xunit.csproj package GitHubActionsTestLogger
            -   name: Run tests
                run: dotnet test --logger GitHubActions tests/Sitko.Core.App.Tests/Sitko.Core.App.Tests.csproj
