name: Blazor

on:
  push:
    branches: [ master ]
    paths:
      - "src/Sitko.Core.Blazor.AntDesign/**"
      - ".github/workflows/blazor.yml"
  pull_request:
    branches: [ master ]
    paths:
      - "src/Sitko.Core.Blazor.AntDesign/**"
      - ".github/workflows/blazor.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/sitkoru/actions-container
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install node.js
        uses: actions/setup-node@v2.3.1
        with:
          node-version: '15'
      - name: Build Sitko.Core.Blazor.AntDesign js
        working-directory: src/Sitko.Core.Blazor.AntDesign/Web
        shell: bash
        run: |
          npm ci
          npm run prod
