name: CI

on:
    push:
        branches: [master, github-actions]

jobs:
    build:
        runs-on: self-hosted
        env:
            VERSION: 3.1.${{ github.run_id }}
            POSTGRES_HOST: localhost
            POSTGRES_HOST_AUTH_METHOD: trust
            XUNIT_USE_POSTGRES: "true"
            MINIO_SERVER_URI: http://localhost:9000
            MINIO_ACCESS_KEY: ptTYf7VkCVbUjAzn
            MINIO_SECRET_KEY: RddqonEnrZZaCU7kkZszN9yiMFkX7rH3
            QUEUE_NATS_HOST: localhost
            SONYFLAKE_URI: http://localhost:8081
        steps:
            -   uses: actions/checkout@v2
            -   name: Restore
                run: dotnet restore --locked-mode
            -   name: Run containers
                run: |
                    docker run -d --rm -p 5432:5432 --name postgres_${{ github.run_id }} postgres:alpine
                    docker run -d --rm -p 9000:9000 --name minio_${{ github.run_id }} minio/minio:latest server /data
                    docker run -d --rm -p 8081:80 --name sonyflake_${{ github.run_id }} titpetric/sonyflake
                    docker run -d --rm -p 4222:4222 --name nats_${{ github.run_id }} nats-streaming:latest -cid tests
            -   name: Tests Sitko.Core.Queue
                run: dotnet test --no-restore /p:Version=$VERSION $(pwd)/tests/Sitko.Core.Queue.Test/Sitko.Core.Queue.Tests.csproj
            -   name: Sitko.Core.Queue.Nats
                run: dotnet test --no-restore /p:Version=$VERSION $(pwd)/tests/Sitko.Core.Queue.Nats.Tests/Sitko.Core.Queue.Nats.Tests.csproj
            -   name: Sitko.Core.Queue.InMemory
                run: dotnet test --no-restore /p:Version=$VERSION $(pwd)/tests/Sitko.Core.Queue.InMemory.Tests/Sitko.Core.Queue.InMemory.Tests.csproj
            -   name: Sitko.Core.Queue.Repository
                run: dotnet test --no-restore /p:Version=$VERSION $(pwd)/tests/Sitko.Core.Repository.Tests/Sitko.Core.Repository.Tests.csproj
            -   name: Sitko.Core.Queue.Sony
                run: dotnet test --no-restore /p:Version=$VERSION $(pwd)/tests/Sitko.Core.SonyFlake.Tests/Sitko.Core.SonyFlake.Tests.csproj
            -   name: Sitko.Core.Queue.Storage.FileSystem
                run: dotnet test --no-restore /p:Version=$VERSION $(pwd)/tests/Sitko.Core.Storage.FileSystem.Tests/Sitko.Core.Storage.FileSystem.Tests.csproj
            -   name: Sitko.Core.Queue.Storage.S3
                run: dotnet test --no-restore /p:Version=$VERSION $(pwd)/tests/Sitko.Core.Storage.S3.Tests/Sitko.Core.Storage.S3.Tests.csproj
            -   name: Stop containers
                run: docker stop postgres_${{ github.run_id }} minio_${{ github.run_id }} sonyflake_${{ github.run_id }} nats_${{ github.run_id }}
            -   name: Create packages
                run: dotnet pack --no-restore -c Release /p:Version=$VERSION -o $(pwd)/nugets
            -   name: Create php packages
                run: |
                    mkdir -p Composer/Core
                    mkdir -p Composer/Queue
                    find $(pwd)/src/Sitko.Core.Grpc/Proto -name "*.proto" | xargs /usr/local/bin/protoc --php_out=$(pwd)/Composer/Core --grpc_out $(pwd)/Composer/Core --proto_path=/opt/include --proto_path=$(pwd)/src/Sitko.Core.Grpc/Proto --plugin=protoc-gen-grpc=/usr/local/bin/grpc_php_client_plugin
                    find $(pwd)/src/Sitko.Core.Queue.Nats/Proto -name "*.proto" | xargs /usr/local/bin/protoc --php_out=$(pwd)/Composer/Queue --proto_path=/opt/include --proto_path=$(pwd)/src/Sitko.Core.Queue.Nats/Proto
