name: Main

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        container: debian:stable
        env:
            APP_VERSION: 4.0.0-ci.${{ github.run_id }}
            POSTGRES_HOST: postgres
            XUNIT_USE_POSTGRES: "true"
            MINIO_SERVER_URI: http://minio:9000
            MINIO_ACCESS_KEY: ptTYf7VkCVbUjAzn
            MINIO_SECRET_KEY: RddqonEnrZZaCU7kkZszN9yiMFkX7rH3
            QUEUE_NATS_HOST: nats
            QUEUE_NATS_CLUSTER_NAME: test-cluster
            SONYFLAKE_URI: http://sonyflake
        services:
            nats:
                image: nats-streaming:latest
            sonyflake:
                image: titpetric/sonyflake
            minio:
                image: bitnami/minio:2020.7.2
                env:
                    MINIO_ACCESS_KEY: ptTYf7VkCVbUjAzn
                    MINIO_SECRET_KEY: RddqonEnrZZaCU7kkZszN9yiMFkX7rH3
            postgres:
                image: postgres:alpine
                env:
                    POSTGRES_HOST_AUTH_METHOD: trust
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup dotnet 3.1
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: '3.1.402'
            -   name: Setup dotnet 5.0
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: '5.0.100-rc.1.20452.10'
            -   name: Restore
                run: dotnet restore --locked-mode
            -   name: Tests Sitko.Core.Queue
                run: dotnet test --no-restore $(pwd)/tests/Sitko.Core.Queue.Test/Sitko.Core.Queue.Tests.csproj
            -   name: Sitko.Core.Queue.Nats
                run: dotnet test --no-restore $(pwd)/tests/Sitko.Core.Queue.Nats.Tests/Sitko.Core.Queue.Nats.Tests.csproj
            -   name: Sitko.Core.Queue.InMemory
                run: dotnet test --no-restore $(pwd)/tests/Sitko.Core.Queue.InMemory.Tests/Sitko.Core.Queue.InMemory.Tests.csproj
            -   name: Sitko.Core.Queue.Repository
                run: dotnet test --no-restore $(pwd)/tests/Sitko.Core.Repository.Tests/Sitko.Core.Repository.Tests.csproj
            -   name: Sitko.Core.Queue.Sony
                run: dotnet test --no-restore $(pwd)/tests/Sitko.Core.SonyFlake.Tests/Sitko.Core.SonyFlake.Tests.csproj
            -   name: Sitko.Core.Queue.Storage.FileSystem
                run: dotnet test --no-restore $(pwd)/tests/Sitko.Core.Storage.FileSystem.Tests/Sitko.Core.Storage.FileSystem.Tests.csproj
            -   name: Sitko.Core.Queue.Storage.S3
                run: dotnet test --no-restore $(pwd)/tests/Sitko.Core.Storage.S3.Tests/Sitko.Core.Storage.S3.Tests.csproj
            -   name: Create packages
                run: dotnet pack --no-restore -c Release /p:Version=$APP_VERSION
