name: Release

on:
    push:
        tags:
            - '*.*.*'

jobs:
    build:
        runs-on: ubuntu-latest
        container: mcr.microsoft.com/dotnet/sdk:5.0
        steps:
            -   uses: actions/checkout@v2.3.4
            -   name: Prepare
                id: prep
                run: |
                    VERSION=${GITHUB_REF#refs/tags/}
                    echo ::set-output name=version::${VERSION}
            -   name: Install node.js
                uses: actions/setup-node@v2.1.5
                with:
                    node-version: '15'
            -   name: Build Sitko.Core.Blazor.AntDesign js
                working-directory: src/Sitko.Core.Blazor.AntDesign/Web
                shell: bash
                run: |
                    npm ci
                    npm run prod
            -   name: Create packages
                run: dotnet pack -c Release /p:Version=${{ steps.prep.outputs.version }} -o $(pwd)/packages
            -   name: Push to Nuget
                run: find packages -type f -name '*.nupkg' -print0 |  xargs -0 -n 10 -P 4 dotnet nuget push -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
            -   name: Download Sitko.Core
                uses: actions/checkout@v2.3.4
                with:
                    repository: "sitkoru/Sitko.Core"
                    path: proto
                    ref: "proto"
            -   name: Publish proto archive
                run: |
                    tar czf proto/proto.tar.gz -C src/Sitko.Core.Grpc/Proto .
                    echo echo ${{ steps.prep.outputs.version }}> proto/VERSION
                    cd proto
                    git config user.name sitkobot
                    git config user.email bot@sitko.ru
                    git add proto.tar.gz
                    git add VERSION
                    git commit -m "publish proto archive ${{ steps.prep.outputs.version }}"
                    git push
                    
